apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: helloworld-controller
  labels:
    app: helloworld
spec:
  replicas: 4
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      app: helloworld
    spec:
      containers:
      - name: k8s-demo
        containerPort: 3000
         
